### ISSUE TITLE
Weird file version  (0.0.1.0) for .net standard package

### ISSUE THREAD

**Issue by larsmarkussen** [dynamicexpresso/DynamicExpresso#161]
Hi

I have a weird issue with the file version of the packages
I am using version 2.8.1, but when installed is file version 0.0.1.0
Any ideas why?
Strange thing is that when downgrading to 2.3.3 which i used to use, is see the same issue, and i am sure it wasnt like that before...

**Comment by davideicardi** [comment]
Hi @larsmarkussen 
Maybe it is because I have changed build pipeline recently and now the version is not set correctly.
Where do you see 0.0.1.0 version exactly?

**Comment by larsmarkussen** [comment]
@davideicardi I see it in the file version
So i have a .net5 project where i use the package. 
I have another project which is .net48, and here is the file version correct

**Comment by davideicardi** [comment]
Probably I just set nuget version but not file version. I will investigate this problem.
Anyway it should not have any real effect I hope. The binary should be correct.

**Comment by metoule** [comment]
The weird version can also be seen in the assembly Version field:

```c#
string assemblyVersion = typeof(DynamicExpresso.Interpreter).Assembly.GetName().Version.ToString();
```

This will impact the demo website that relies on that field to display the current DynamicExpresso version (so it should ideally be fixed before #179).

**Comment by davideicardi** [comment]
Maybe we can use this solution https://stackoverflow.com/a/53067759/209727 ?

**Comment by metoule** [comment]
Actually I think it's far simpler: in `publish.yml`, the `dotnet test` step rebuilds the assembly, but without the version flag!
To avoid this issue, I think all steps should have the ` --no-build` flag added.
