### ISSUE TITLE
Automatic conversion of string parameter values to numeric values

### ISSUE THREAD

**Issue by ElderJames** [dynamicexpresso/DynamicExpresso#181]
I want to be able to pass string numbers as parameters for mathematical expressions. 
Because I save the parameter value to the database as a number string.

```cs
var interpreter = new Interpreter();

var parameters = new[] {
	new Parameter("x", "23"),
};

Assert.AreEqual(30, interpreter.Eval("x + 7", parameters));
```

**Comment by davideicardi** [comment]
Hi @ElderJames ,
Why not just converting the parameter to a number when creating the parameter?
