### ISSUE TITLE
Lambda Expressions break type detection after refactor in 2.9.5

### ISSUE THREAD

**Issue by bluba** [dynamicexpresso/DynamicExpresso#197]
Hi, it seems like changes introduced after release of 2.9.4  broke type parsing when lambda expressions are enabled.

            var interpreterWithLambdas = new Interpreter(InterpreterOptions.DefaultCaseInsensitive | InterpreterOptions.LambdaExpressions);
            var interpreterWithoutLambdas = new Interpreter(InterpreterOptions.DefaultCaseInsensitive);

            var stringExpression = "booleanValue ? someStringValue : \".\"";
            var parameters = new List<Parameter>();

            parameters.Add(new Parameter($"someStringValue", typeof(string), $"E33"));
            parameters.Add(new Parameter("booleanValue", typeof(bool), true));

            var expressionWithoutLambdas = interpreterWithoutLambdas.Parse(stringExpression, typeof(void), parameters.ToArray());
            Console.WriteLine(expressionWithoutLambdas.Invoke(parameters.ToArray()));

            var expressionWithLambdas = interpreterWithLambdas.Parse(stringExpression, typeof(void), parameters.ToArray());
            Console.WriteLine(expressionWithLambdas.Invoke(parameters.ToArray()));

In version 2.9.4 both interpreters produce correct result of "E33" but on version 2.9.5 and 2.9.6 Object reference not set to an instance of an object. is thrown from
`var expressionWithLambdas = interpreterWithLambdas.Parse(stringExpression, typeof(void), parameters.ToArray());`

**Comment by metoule** [comment]
Thanks for reporting! That was a side effect of PR #178, and was an easy fix.

**Comment by bluba** [comment]
Thanks for your work and quick fix.
