### ISSUE TITLE
TryParse method without throwing exception

### ISSUE THREAD

**Issue by halamah** [dynamicexpresso/DynamicExpresso#204]
Haven't found al alternative way to parse without throwing exception. This would be handy if one needs to suppress exception or exception info is not needed in execution context. 

Suppressing exception could also increase performance in case of multiple parses.

```c#
var isSuccess = interpreter.TryParse(expression, out var lambda);
```

**Comment by metoule** [comment]
Can't you simply add an extension method that suits your needs? That's probably how it would be implemented any way..

```c#
public static bool TryParse(this Interpreter interpreter, string expressionText, out Lambda lambda)
{
  try
  {
    lambda = interpreter.Parse(expressionText);
    return true;
  }
  catch
  {
    lambda = null;
    return false;
  }
}

```

**Comment by davideicardi** [comment]
@halamah there is also a DetectIdentifiers function:
https://github.com/dynamicexpresso/DynamicExpresso#identifiers-detection

Maybe this can be useful for your use case? Or can you elaborate it a little bit more?

**Comment by halamah** [comment]
Yep, I'm using both suggestions above at the moment. Thanks.
