### ISSUE TITLE
Does it support bitwise operations

### ISSUE THREAD

**Issue by ygl-rg** [dynamicexpresso/DynamicExpresso#206]
Hi

   I like this prj and want to use it for our iot applications

Our user cases involve bitwise operations which I am not sure are supported or not.

Regards

Ygl

**Comment by metoule** [comment]
Relevant C# documentation: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators

It seems that they're not:

```c#
var target = new Interpreter();
var x = 0b_1100_1001_0000_0000_0000_0000_0001_0001;
target.SetVariable("x", x);

// operators not implemented
Assert.Equal(~x, target.Eval<uint>("~x"));
Assert.Equal(x >> 4, target.Eval<uint>("x >> 4"));
Assert.Equal(x << 4, target.Eval<uint>("x << 4"));

// failure to resolve the operator
Assert.Equal(x & 4, target.Eval<uint>("x & 4"));
Assert.Equal(x | 4, target.Eval<uint>("x | 4"));
Assert.Equal(x ^ 4, target.Eval<uint>("x ^ 4"));
```

**Comment by metoule** [comment]
@ygl-rg do you have some example of the kind of operations you're likely to encounter?
