### ISSUE TITLE
.NET Framework 4.5.2 end of support is April 26, 2022

### ISSUE THREAD

**Issue by metoule** [dynamicexpresso/DynamicExpresso#224]
DynamicExpresso is configured for multi-targeting:

```xml
<TargetFrameworks>netstandard2.0;net461;net45</TargetFrameworks>
```

.NET 4.5 is reaching [end of support on April 26, 2022](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework):

![image](https://user-images.githubusercontent.com/24547430/151872373-b713cb12-3f78-428c-ba76-3a284be01eab.png)

That means that the lowest supported version of .NET Framework is now .NET 4.6.2, which is [compatible with `netstandard2.0`](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0).

Therefore, I suggest the following: 
* only target `netstandard2.0` in DynamicExpresso.Core
* target `netcoreapp5.0;netcoreapp3.1;net462` in DynamicExpresso.UnitTest

**Comment by metoule** [comment]
@davideicardi what do you think?

**Comment by davideicardi** [comment]
@metoule  Fine for me! Good idea!

**Comment by metoule** [comment]
I think it will probably need a version bump to 3.0.0 though, because it's a breaking change. 
If needed, here's a SO question to [use .NET4.5 with VS2022](https://stackoverflow.com/questions/70022194/open-net-framework-4-5-project-in-vs-2022-is-there-any-workaround).
