### ISSUE TITLE
Interpreter Scope identifier support

### ISSUE THREAD

**Issue by halamah** [dynamicexpresso/DynamicExpresso#232]
It would be very convenient to add a Scope support into Interpreter. Consider the following snippet:

```c#
record Person(string Name, string Gender, int Age);

var interpreter = new Interpreter();

// this is a proposed Scope feature
interpreter.UseScope<Person>();

var person = new Person("Ulrich", "Male", 30);

var lambda = interpreter.Parse("Gender == \"Male\" && Age >= 30"); 

Assert.True(lambda.Invoke(person));
```

So it looks like a `this` reference that is implicitly passed when calling class methods. 

Although I can pass a person object itself as a variables - this will make the expression more complex i.e. `"person.Gender == \"Male\" && person.Age >= 30"` what is less convenient and not concise.

**Comment by davideicardi** [comment]
Yes, similar requirement came up also in the past, like #18  (back in 2014 ;-) ).
I agree that in some context it could be nice, on the other end it could add some complexity in the parser ... If you find some nice way to implement this feature I think it could be added.

**Comment by halamah** [comment]
closing this one to track further in https://github.com/dynamicexpresso/DynamicExpresso/pull/233
