### ISSUE TITLE
HEX (0x) or binary (0b) value support

### ISSUE THREAD

**Issue by mocakturk** [dynamicexpresso/DynamicExpresso#236]
Library does not support hex number (e.g. 0xABC) or binary number (e.g. 0b1101).
I need to replace hex/binary numbers using regular expression before evaluation.

Here example expression:
"4 + 0xA1"

The result should be 165.

**Comment by metoule** [comment]
Relevant documentation: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#6453-integer-literals
