### ISSUE TITLE
Math.Round not working with InterpreterOptions.CaseInsensitive option.

### ISSUE THREAD

**Issue by drebat** [dynamicexpresso/DynamicExpresso#243]
I have two formulas read from a database:
  -   "Math.Round(PREMIUM * MODAL_FACTOR, 2)"
  -   "Math.Round(PREMIUM * modal_factor, 2)"

My variables are always upper case so I tried using the InterpreterOptions.CaseInsensitive option. However, when I create the interpreter with the InterpreterOptions.CaseInsensitive option, 'Math' is no longer recognized.

This works (C#):
`var calculator = new Interpreter().SetVariable("PREMIUM", 100000d);`
`var basePremium = calculator.Eval<double>("Math.Round(PREMIUM * MODAL_FACTOR, 2)", new[] { new Parameter("MODAL_FACTOR", 1d) });`

Unknown identifier 'modal_factor':
`var calculator = new Interpreter().SetVariable("PREMIUM", 100000d);`
`var basePremium = calculator.Eval<double>("Math.Round(PREMIUM * modal_factor, 2)", new[] { new Parameter("MODAL_FACTOR", 1d) });`

Unknown identifier 'Math':
`var calculator = new Interpreter(InterpreterOptions.CaseInsensitive).SetVariable("PREMIUM", 100000d);`
`var basePremium = calculator.Eval<double>("Math.Round(PREMIUM * modal_factor, 2)", new[] { new Parameter("MODAL_FACTOR", 1d) });`

**Comment by metoule** [comment]
Hi @drebat, sorry for the late reply.

You should simply use `InterpreterOptions.DefaultCaseInsensitive` instead of `InterpreterOptions.CaseInsensitive`. Otherwise, the `Math` class is not imported. 

```c#
var calculator = new Interpreter(InterpreterOptions.DefaultCaseInsensitive).SetVariable("PREMIUM", 100000d);
var basePremium = calculator.Eval<double>("Math.Round(PREMIUM * modal_factor, 2)", new Parameter("MODAL_FACTOR", 1d) );
```
