### ISSUE TITLE
Does DynamicExpresso has any expression editor?

### ISSUE THREAD

**Issue by evolcano** [dynamicexpresso/DynamicExpresso#255]
DynamicExpresso is good enough to parse and evaluate expressions. I need a visual expression editor to enable the user to create User-define expressions.

1、Does someone already add a expression editor to DynamicExpresso ?
2、or recommend some relevant repository to reference if someone want to implement it?

**Comment by davideicardi** [comment]
As I know there isn't any ready to use editor. In the past I have used https://codemirror.net/, that can be customized for such use cases.
