### ISSUE TITLE
Bitwise complement operator ~

### ISSUE THREAD

**Issue by rkaderli** [dynamicexpresso/DynamicExpresso#261]
I have expression using  [Flags]enum type where I would like to reset a bit using like "b = ~a;"

See also https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#bitwise-complement-operator-

Is there a way to get this done?  opposite operation with | works just fine.

**Comment by metoule** [comment]
I forgot to handle the unary operators in #237 ... It should be pretty straightforward to implement.
