### ISSUE TITLE
Call a custom method. The parameter is an expression

### ISSUE THREAD

**Issue by syyqdsxfdmy** [dynamicexpresso/DynamicExpresso#262]
hi,everyone
I have a custom method as follows：
![image](https://user-images.githubusercontent.com/6846622/201695028-f8703bc0-8085-4f2e-b0fc-1061b24d6a88.png)

I call it as follows, but an error is reported。
![image](https://user-images.githubusercontent.com/6846622/201694810-00d0d335-25d9-452f-8e66-445fae68b7b1.png)

What should I do? Thank you

**Comment by davideicardi** [comment]
Can you try to create a small unit test to reproduce the error, with as little code as possible?
thank you!

**Comment by metoule** [comment]
Analysis and reproduction code in the PR.
