### ISSUE TITLE
Interpreter.DetectIdentifiers can not find non-ascii identifier in expression

### ISSUE THREAD

**Issue by littepointR** [dynamicexpresso/DynamicExpresso#269]
My test code is:

    var identifiersInfo    = interpreter.DetectIdentifiers("中文");
    var identifiers        = identifiersInfo.Identifiers.ToArray();
    var unknownIdentifiers = identifiersInfo.UnknownIdentifiers.ToArray();
    var referenceTypes     = identifiersInfo.Types.ToArray();
    Console.WriteLine("Chinese --> ");
    Console.WriteLine($"identifiers.Count = {identifiers.Length}");
    Console.WriteLine($"unknownIdentifiers.Count = {unknownIdentifiers.Length}");
    Console.WriteLine($"referenceTypes.Count = {referenceTypes.Length}");

    var identifiersInfo    = interpreter.DetectIdentifiers("日本語");
    var identifiers        = identifiersInfo.Identifiers.ToArray();
    var unknownIdentifiers = identifiersInfo.UnknownIdentifiers.ToArray();
    var referenceTypes     = identifiersInfo.Types.ToArray();
    Console.WriteLine("Japanese --> ");
    Console.WriteLine($"identifiers.Count = {identifiers.Length}");
    Console.WriteLine($"unknownIdentifiers.Count = {unknownIdentifiers.Length}");
    Console.WriteLine($"referenceTypes.Count = {referenceTypes.Length}");

    var identifiersInfo    = interpreter.DetectIdentifiers("русский язык");
    var identifiers        = identifiersInfo.Identifiers.ToArray();
    var unknownIdentifiers = identifiersInfo.UnknownIdentifiers.ToArray();
    var referenceTypes     = identifiersInfo.Types.ToArray();
    Console.WriteLine("Russian --> ");
    Console.WriteLine($"identifiers.Count = {identifiers.Length}");
    Console.WriteLine($"unknownIdentifiers.Count = {unknownIdentifiers.Length}");
    Console.WriteLine($"referenceTypes.Count = {referenceTypes.Length}");

and ouput:

    Chinese -->
    identifiers.Count = 0
    unknownIdentifiers.Count = 0
    referenceTypes.Count = 0
    Japanese -->
    identifiers.Count = 0
    unknownIdentifiers.Count = 0
    referenceTypes.Count = 0
    Russian -->
    identifiers.Count = 0
    unknownIdentifiers.Count = 0
    referenceTypes.Count = 0

**Comment by littepointR** [comment]
It seems because the regex Detector.IdentifiersDetectionRegex only matches a-zA-Z

**Comment by davideicardi** [comment]
Yes, probably the regex could be extended in same way. As usual any help is appreciated ...

**Comment by gaoqiangz** [comment]
Any progress?

**Comment by KaivnD** [comment]
I need this Identifiers Detector support this too, then ChatGPT give the solution like this.
```diff
- private static readonly Regex IdentifiersDetectionRegex = new Regex(@"([^\.]|^)\b(?<id>[a-zA-Z_]\w*)\b", RegexOptions.Compiled);
+ private static readonly Regex IdentifiersDetectionRegex = new Regex(@"([^\.]|^)\b(?<id>[\p{L}_]\w*)\b", RegexOptions.Compiled);
```
which gives a regex `([^\.]|^)\b(?<id>[\p{L}_]\w*)\b` for both acsii and non-acsii identifier,
here is test from [regex101](https://regex101.com/r/44WO9x/1)
works for me.

**Comment by metoule** [comment]
Relevant section of the C# specifications: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#643-identifiers
