### ISSUE TITLE
Parsing exception while using 'as' operator

### ISSUE THREAD

**Issue by pawel1708hp** [dynamicexpresso/DynamicExpresso#287]
I'm trying to use following expression:

`string.IsNullOrEmpty(variable as string)`

but it results with exception: DynamicExpresso.Exceptions.ParseException: ')' or ',' expected (at index 40).

Adding extra parenthesis as message suggests solves the issue, but the expression is obviously wrong then
`string.IsNullOrEmpty(variable as string))`

Seems there is something wrong with parser.

**Comment by pawel1708hp** [comment]
Well, according to documentation it is supported ;)
![image](https://github.com/dynamicexpresso/DynamicExpresso/assets/13347601/6e43c683-8253-404f-ad03-d7d56c09ec06)

**Comment by IAMJDA** [comment]
We have the exact issue since upgrading to a newer version. Expressions which worked before, now break.

**Comment by davideicardi** [comment]
It could be a regression. could you help us by telling us from which version it stopped working?

**Comment by IAMJDA** [comment]
Before: 2.8.1.0
After: 2.10.0.0

Test for As_Operator:
`Assert.AreEqual(string.IsNullOrEmpty(a as string), target.Eval("string.IsNullOrEmpty(a as string)"));`

**Comment by IAMJDA** [comment]
Manual bisect:
- 2.9.5 fails
- 2.9.4 works

#178 seems to be to blame

**Comment by metoule** [comment]
@IAMJDA thanks for narrowing it down! It's indeed a regression in the way the types are parsed: we don't reset the parser position properly if the type has no modifier. I'll need to ensure it's working for all the possible type modifiers. For example:

```C#
string?
string?[]
string?[][]
IEnumerable<string>
IEnumerable<string?[]>?[]
``` 
but it shouldn't take too long 🤞
