### ISSUE TITLE
DetectIdentifiers parsing decimals with suffix are considered as Identifier

### ISSUE THREAD

**Issue by tyl24** [dynamicexpresso/DynamicExpresso#300]
Hello,
In the DetectIdentifiers method an expression like this one : "amount=Math.Round(455.7 * (0.2m/1000))"
considere that the decimal suffix m is an unknownIdentifier, which is wrong !
This behaviours was not the case in previous version 2.13.

In file Detector.cs, I propose to change the RegEx :IdentifiersDetectionRegex like this :
`(?<id>@?(?<!\d)(?<!\dm)(?<!\df)(?<!\dd)[\p{L}\p{Nl}_][\p{L}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Pc}\p{Cf}_]*)`

**Comment by davideicardi** [comment]
Thank you! If you are able to create a PR I can merge it. Otherwise I will do it.
