### ISSUE TITLE
Using culture in parser ?

### ISSUE THREAD

**Issue by FabriceAeby** [dynamicexpresso/DynamicExpresso#310]
Hi,

Is is possible to define the culture of the parser ? I've french users that are using a ',' comma to delimit double digits. 

Currently I've an exception when evaluating the simple script "2,5 + 10" for example.

Thank for your help and Kind Regards,
Fabrice

**Comment by davideicardi** [comment]
No, I'm sorry. This is not possible because comma is a special character in C#, and Dynamic Expresso try mimic C# language.
