### ISSUE TITLE
DetectIdentifiers only returns the last part of the identifiers

### ISSUE THREAD

**Issue by alesanchez-windifferent** [dynamicexpresso/DynamicExpresso#322]
If i have a query like this "Contact.First_Name = "Alejandro" && Company.Foundation = 2008"
The detectIdentifier only returns "Contact" and "Company" in the UnknownIdentifiers.
I have an implementation to test to return the complete variables, as an optional parameter to the current method.
Can i send the PR? Would it be useful?

**Comment by davideicardi** [comment]
Thank you! I will review it.
