### ISSUE TITLE
Broken localization

### ISSUE THREAD

**Issue by cpiber** [dynamicexpresso/DynamicExpresso#328]
#318 broke localization

Some strings are still localized (e.g. `ErrorMessages.Format` is still used), but many actually useful messages are hardcoded again, like "Unknown identifier"
https://github.com/dynamicexpresso/DynamicExpresso/blob/590910db84145fcbc268258cc20739e931882c44/src/DynamicExpresso.Core/Exceptions/UnknownIdentifierException.cs#L10

**Comment by davideicardi** [comment]
Thank you for the issue. You are right. We will try to resolve this issue in the future. As usual, any help is appreciated ;-) .

**Comment by cpiber** [comment]
@metoule My PR that fixes it is already merged, I forgot to close this
