### ISSUE TITLE
Why does the expression (20/50) evaluate to 0?

### ISSUE THREAD

**Issue by landonzeng** [dynamicexpresso/DynamicExpresso#335]
![image](https://github.com/user-attachments/assets/c904a8e7-3d94-4d8f-ac4c-99d9cd636d03)
Why is the expression (20/50) evaluated to 0? Can you set globally how much to return when evaluating the expression?

**Comment by davideicardi** [comment]
I think that depends on the type of variables. If you are using integers the result is also an integer. If you are using doubles or floats or decimals the results will have more precision. This is the standard C# behavior, and in DynamicExpresso we try to mimic it. But we have a settings to force all numbers to be something else. See https://github.com/dynamicexpresso/DynamicExpresso?tab=readme-ov-file#default-number-type

**Comment by landonzeng** [comment]
> I think that depends on the type of variables. If you are using integers the result is also an integer. If you are using doubles or floats or decimals the results will have more precision. This is the standard C# behavior, and in DynamicExpresso we try to mimic it. But we have a settings to force all numbers to be something else. See https://github.com/dynamicexpresso/DynamicExpresso?tab=readme-ov-file#default-number-type

Thanks! The SetDefaultNumberType method solved my problem, just set SetDefaultNumberType (DefaultNumberType.Decimal) and it's ok!
