### ISSUE TITLE
When calculating an expression, an error is reported if the expression has [] in it.

### ISSUE THREAD

**Issue by landonzeng** [dynamicexpresso/DynamicExpresso#337]
Error in calculation of (-CWPT_007_P)+[1-(-0.3)]: Expression expected (at index 14).
![image](https://github.com/user-attachments/assets/5624a32b-c9c0-433e-a5f3-76929956502e)
![image](https://github.com/user-attachments/assets/30935da8-53a4-455d-a397-6f795b791f52)
![image](https://github.com/user-attachments/assets/09314af5-46ef-42ec-a6d8-3591aa874f3c)

**Comment by davideicardi** [comment]
Can you post some actual text code to reproduce the problem?

**Comment by metoule** [comment]
You're using brackets as parenthesis, which is not supported:

```c#
(-23)+[1-(-0.3)]
```

should be 

```c#
(-23)+(1-(-0.3))
```

**Comment by landonzeng** [comment]
> You're using brackets as parenthesis, which is not supported:
> 
> ```cs
> (-23)+[1-(-0.3)]
> ```
> 
> should be
> 
> ```cs
> (-23)+(1-(-0.3))
> ```

I can understand using parentheses to replace square brackets, e.g. (-23)+(1-(-0.3)), but there are square bracketed expressions in mathematical logic, which can be confusing for the user

**Comment by landonzeng** [comment]
> Can you post some actual text code to reproduce the problem?

Sample code for example:
```cs
static void Main(string[] args)
{
    var interpreter = new Interpreter();
    var parameters = new[] {
        new Parameter("CWPT_007_P", 23),
        new Parameter("CWPT_007_S", -0.3),
    };
    var dd = interpreter.Eval("(-CWPT_007_P)+[1-(CWPT_007_S+5)]", parameters);  
    Console.WriteLine($"dd : {dd}");
}
```

**Comment by davideicardi** [comment]
I agree with you @landonzeng , but DynamicExpresso is not a math interpreter, the goal is to create a C# interpreter.
If you realy want to use DynamicExpresso for math maybe you can try to do some preprocessing first, for example replacing `[ ]` with `( )`. But I suspect that it is not the right tool to be honest.

**Comment by landonzeng** [comment]
> I agree with you @landonzeng , but DynamicExpresso is not a math interpreter, the goal is to create a C# interpreter. If you realy want to use DynamicExpresso for math maybe you can try to do some preprocessing first, for example replacing `[ ]` with `( )`. But I suspect that it is not the right tool to be honest.

Yes, that's what I thought too, now I'll just have to replace [] with () to take care of business
